/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatclient;

import java.awt.CardLayout;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.text.DefaultCaret;
import static javax.swing.text.DefaultCaret.ALWAYS_UPDATE;

/**
 *
 * @author beyza
 */
public class ClientFrame extends javax.swing.JFrame {

    /**
     * Creates new form ClientFrame
     */
    
    CardLayout cardLayout;
    DefaultListModel dlm;
    
    public ClientFrame() {
        initComponents();
     
      
      try{
          UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
      }catch(Exception e){
          System.out.println(e.toString());
      }
        
        init_frame();
    }
    
    void init_frame(){
        
        chatBoxField.setLineWrap(true);
        chatBoxField.setWrapStyleWord(true);
        
        cardLayout = (CardLayout)getContentPane().getLayout();
        cardLayout.show(getContentPane(), "menuCard");
        
        dlm = new DefaultListModel();
        connectedClientList.setModel(dlm);
        
        DefaultCaret caret = (DefaultCaret)(chatBoxField.getCaret());
        caret.setUpdatePolicy(ALWAYS_UPDATE);
        
        
    }

    public DefaultListModel getDlm() {
        return dlm;
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        onlinePanel = new javax.swing.JPanel();
        listPane = new javax.swing.JScrollPane();
        connectedClientList = new javax.swing.JList<>();
        exitButton = new javax.swing.JButton();
        startChat_button = new javax.swing.JButton();
        startchatroom_button = new javax.swing.JButton();
        messagesPane = new javax.swing.JScrollPane();
        chatBoxField = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        chatNameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        writeMessageField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fileChooserButton = new javax.swing.JButton();
        menuPanel = new javax.swing.JPanel();
        menuIconLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        connectButton = new javax.swing.JButton();
        menuMessageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("hey!");
        setBackground(new java.awt.Color(51, 255, 102));
        setPreferredSize(new java.awt.Dimension(950, 750));
        getContentPane().setLayout(new java.awt.CardLayout());

        onlinePanel.setBackground(new java.awt.Color(232, 239, 251));
        onlinePanel.setForeground(new java.awt.Color(232, 239, 251));
        onlinePanel.setPreferredSize(new java.awt.Dimension(810, 661));
        onlinePanel.setLayout(new java.awt.GridBagLayout());

        listPane.setAutoscrolls(true);

        connectedClientList.setPreferredSize(new java.awt.Dimension(200, 300));
        listPane.setViewportView(connectedClientList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 97;
        gridBagConstraints.insets = new java.awt.Insets(39, 0, 9, 0);
        onlinePanel.add(listPane, gridBagConstraints);

        exitButton.setText("Çıkış");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 0;
        onlinePanel.add(exitButton, gridBagConstraints);

        startChat_button.setText("Özel Konuşma Başlat");
        startChat_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startChat_buttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        onlinePanel.add(startChat_button, gridBagConstraints);

        startchatroom_button.setText("Konuşma Odası Başlat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        onlinePanel.add(startchatroom_button, gridBagConstraints);

        messagesPane.setHorizontalScrollBar(null);
        messagesPane.setPreferredSize(new java.awt.Dimension(400, 400));

        chatBoxField.setEditable(false);
        chatBoxField.setColumns(20);
        chatBoxField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        chatBoxField.setRows(5);
        chatBoxField.setText("Hey! de");
        chatBoxField.setCaretPosition(0);
        chatBoxField.setPreferredSize(new java.awt.Dimension(400, 400));
        messagesPane.setViewportView(chatBoxField);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.insets = new java.awt.Insets(38, 25, 8, 25);
        onlinePanel.add(messagesPane, gridBagConstraints);

        sendButton.setText("Gönder");
        sendButton.setPreferredSize(new java.awt.Dimension(75, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 22);
        onlinePanel.add(sendButton, gridBagConstraints);

        chatNameLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chatNameLabel.setText("Genel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 24, 0, 5);
        onlinePanel.add(chatNameLabel, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("hey!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        onlinePanel.add(jLabel1, gridBagConstraints);

        writeMessageField.setPreferredSize(new java.awt.Dimension(290, 40));
        writeMessageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writeMessageFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 80);
        onlinePanel.add(writeMessageField, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Bağlı Kullanıcılar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        onlinePanel.add(jLabel2, gridBagConstraints);

        fileChooserButton.setText("...");
        fileChooserButton.setPreferredSize(new java.awt.Dimension(45, 45));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 21, 0, 0);
        onlinePanel.add(fileChooserButton, gridBagConstraints);

        getContentPane().add(onlinePanel, "onlineCard");

        menuPanel.setBackground(new java.awt.Color(232, 239, 251));
        menuPanel.setForeground(new java.awt.Color(232, 239, 251));
        menuPanel.setToolTipText("");
        menuPanel.setPreferredSize(new java.awt.Dimension(800, 700));
        menuPanel.setLayout(new java.awt.GridBagLayout());

        menuIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        menuIconLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridheight = 14;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 34, 0);
        menuPanel.add(menuIconLabel, gridBagConstraints);

        usernameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameTextField.setText("Kullanıcı Adı");
        usernameTextField.setMaximumSize(new java.awt.Dimension(150, 60));
        usernameTextField.setMinimumSize(new java.awt.Dimension(150, 60));
        usernameTextField.setPreferredSize(new java.awt.Dimension(150, 60));
        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        menuPanel.add(usernameTextField, gridBagConstraints);

        connectButton.setText("Bağlan");
        connectButton.setPreferredSize(new java.awt.Dimension(150, 60));
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        menuPanel.add(connectButton, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 27;
        menuPanel.add(menuMessageLabel, gridBagConstraints);

        getContentPane().add(menuPanel, "menuCard");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_connectButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        // to do closing connections etc
        cardLayout.show(getContentPane(), "menuCard");
    }//GEN-LAST:event_exitButtonActionPerformed

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void startChat_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startChat_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startChat_buttonActionPerformed

    private void writeMessageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writeMessageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_writeMessageFieldActionPerformed

     public JList<String> getConnectedClientList() {
        return connectedClientList;
    }

    public JButton getStartChat_button() {
        return startChat_button;
    }

    public JButton getStartchatroom_button() {
        return startchatroom_button;
    }
        //</editor-fold>

    public JButton getExitButton() {
        return exitButton;
    }

 
    
    public JButton getConnectButton() {
        return connectButton;
    }

    public JButton getSendButton() {
        return sendButton;
    }

    public JTextField getWriteMessageField() {
        return writeMessageField;
    }

    public JTextArea getChatBoxField() {
        return chatBoxField;
    }

    public JButton getFileChooserButton() {
        return fileChooserButton;
    }
    
    
   

  
    

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ClientFrame().setVisible(true);
//            }
//        });
//    }

    public JTextField getUsernameTextField() {
        return usernameTextField;
    }

    public JLabel getMenuMessageLabel() {
        return menuMessageLabel;
    }
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea chatBoxField;
    private javax.swing.JLabel chatNameLabel;
    private javax.swing.JButton connectButton;
    private javax.swing.JList<String> connectedClientList;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton fileChooserButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane listPane;
    private javax.swing.JLabel menuIconLabel;
    private javax.swing.JLabel menuMessageLabel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JScrollPane messagesPane;
    private javax.swing.JPanel onlinePanel;
    private javax.swing.JButton sendButton;
    private javax.swing.JButton startChat_button;
    private javax.swing.JButton startchatroom_button;
    private javax.swing.JTextField usernameTextField;
    private javax.swing.JTextField writeMessageField;
    // End of variables declaration//GEN-END:variables
}
